apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarm
  labels:
    app: alarm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alarm
  template:
    metadata:
      labels:
        app: alarm
    spec:
      containers:
        - name: alarm
          image: 422443478711.dkr.ecr.ap-northeast-2.amazonaws.com/alarm:2024-07-08T17-43-54
          volumeMounts:
            - name: persistent-storage
              mountPath: /upload
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: efs-claim
