apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-test
  template:
    metadata:
      labels:
        app: eks-test
    spec:
      containers:
        - name: eks-test
          image: pengbai/docker-supermario
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'