apiVersion: apps/v1
kind: Deployment
metadata:
  name: encoder
  labels:
    app: encoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: encoder
  template:
    metadata:
      labels:
        app: encoder
    spec:
      containers:
        - name: encoder
          image: 422443478711.dkr.ecr.ap-northeast-2.amazonaws.com/encoder:2024-07-08T17-43-54
          volumeMounts:
            - name: persistent-storage
              mountPath: /upload
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: efs-claim
