apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery
  labels:
    app: gallery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gallery
  template:
    metadata:
      labels:
        app: gallery
    spec:
      containers:
        - name: gallery
          image: 422443478711.dkr.ecr.ap-northeast-2.amazonaws.com/gallery:2024-07-08T17-43-54
          volumeMounts:
            - name: persistent-storage
              mountPath: /upload
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: efs-claim
